trigger:
- main

pool:
  name: 'MySelfHostedPool'          
  demands:
  - Agent.Name -equals hssah-agent

steps:
- checkout: self

- script: python --version
  displayName: 'Check Python'

- script: pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: python -m pytest -q
  displayName: 'Run tests'
  continueOnError: true
