trigger:
- main

pool:
  name: MySelfHostedPool

variables:
  azureServiceConnectionId: 'sc-hssah-ml'        
  webAppName: 'hssah-ml-1755027380'             
  environmentName: 'prod'

stages:
# ======================
# Build Stage
# ======================
- stage: Build
  displayName: Build & Package
  jobs:
  - job: BuildJob
    displayName: BuildJob
    pool:
      name: MySelfHostedPool
    steps:
    - checkout: self

    - powershell: |
        python -m pip install --upgrade pip
        New-Item -ItemType Directory -Force -Path ".python_packages\lib\site-packages" | Out-Null
        python -m pip install -r requirements.txt -t ".python_packages\lib\site-packages"
      displayName: Install dependencies (vendored)

    - powershell: |
        python -m pip install pylint
        pylint --disable=C,R app.py
        if ($LASTEXITCODE -ne 0) { Write-Host "Lint warnings ignored"; exit 0 }
      displayName: Lint (non-blocking)

    - task: ArchiveFiles@2
      displayName: Archive app
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)\drop.zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      displayName: Publish artifact
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

# ======================
# Deploy Stage
# ======================
- stage: Deploy
  displayName: Deploy to Azure Web App
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployWeb
    displayName: DeployWeb
    environment: '$(environmentName)'
    pool:
      name: MySelfHostedPool
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            displayName: Download artifact
            artifact: drop

          - task: AzureWebApp@1
            displayName: Deploy Azure Web App
            inputs:
              azureSubscription: '$(azureServiceConnectionId)'
              appName: '$(webAppName)'
              appType: 'webApp'        
              package: '$(Pipeline.Workspace)\drop\drop.zip'
